name: unicrawl
channels:
  - defaults
  - conda-forge
  - anaconda
  - bioconda
dependencies:
  - scrapy
  - pandas
  - protego
  - tqdm
  - unidecode
  - scikit-learn
  - spacy
  - langdetect
  - snakemake-minimal